exclude: .*migrations\/.*,.static\/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-toml
      - id: check-ast
      - id: debug-statements
      - id: check-merge-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py313-plus]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.25.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.2"]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.5'
    hooks:
      - id: bandit

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
        args: [ "--configuration=pyproject.toml" ]
      - id: djlint-django
        args: ["--configuration=pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        exclude: ^(tests/|flower_healthcheck\.py)$

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
      - id: autopep8

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      # Run the linter with custom arguments.
      - id: ruff-check
        args: [ "--preview", "--ignore=D211,D213", "--config=pyproject.toml", "--output-format=github", "--diff", "--exclude=auth/migrations,geo_api/migrations,manage.py,db_api/migrations,dashboards/migrations", "--fix" ]
